main: firstAttempt.App
name: BlankPlugin
version: 0.1

commands:
  demo: #指令名
    description: "测试指令" #指令的注解
    usage: /demo #指令的用法 当onCommand()方法返回false时提示这里的内容
    aliases: [d,de] #指令的多种形式 意为可以用 d, de 来触发/demo这个指令
    permission: "demo.use" #指令所需要的权限
    permission-message: "无权使用" #当输入者无上方权限时提示该信息